[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino

monitor_speed = 115200
upload_speed = 921600

monitor_port = /dev/ttyACM0
upload_port  = /dev/ttyACM0

monitor_filters = direct
monitor_dtr = 0
monitor_rts = 0

build_flags =
    -DCORE_DEBUG_LEVEL=0

lib_deps =
     bblanchon/ArduinoJson @ ^6.21.0
    adafruit/Adafruit SSD1306 @ ^2.5.7
    adafruit/Adafruit GFX Library @ ^1.11.5